### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by E3V3A** [derhuerst/flightradar24-client#10]
Tried to run the example.js with different lat/lon and get the following error:

```bash
$ ./testradar.js
TypeError: Cannot read property 'id' of undefined
    at radar.then (/home/pi/testradar.js:10:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by E3V3A** [comment]
This happens when there are no planes in the area.

**Comment by derhuerst** [comment]
Can you post your example code?

**Comment by E3V3A** [comment]
its the same as yours, just put a bounding box where there are no planes.

**Comment by derhuerst** [comment]
Please give me your full code.

**Comment by E3V3A** [comment]
`radar(85,13,84,14)` ! When there are no planes, your test script fails.

**Comment by derhuerst** [comment]
In a way, that's intended. There's no real way to check if the client properly parses the data from the API, so the test expects one or more flights. In 49cd6e0, I've made the tests fail up front if there are no flights.

**Comment by E3V3A** [comment]
Yeah, I see what you mean. 

Sorry I wasn't very specific. But I was hoping to fix it in the library somewhere [around here](https://github.com/derhuerst/flightradar24-client/blob/master/lib/radar.js#L64-L69) and instead return something we can more easily check, rather than "crashing".  Especially since JS have [this funny](https://www.w3schools.com/js/tryit.asp?filename=tryjs_type_convert_array_empty) way of treating an empty list `[]` as a Boolean *True*, while turning the number converted one into a zero!  I haven't tried the full query to see what is actually returned by the Fr24 JSON upon empty set.
