### ISSUE TITLE
add hint that the altitude is in feet

### ISSUE THREAD

**Issue by E3V3A** [derhuerst/flightradar24-client#11]
Int'l standard seem to benefit `meters` as a altitude unit. 
Please consider converting the [result](https://github.com/derhuerst/flightradar24-client/blob/master/lib/radar.js#L82)  to meters.

**Comment by derhuerst** [comment]
Hm. While meters are definitely the more consistent and scientific unit, I'm not sure if that belongs into this library. It's easy to convert the value using [`feed-to-meters`](https://github.com/joshause/feettometers).

**Comment by derhuerst** [comment]
It would be really helpful to put a comment in the example response in the readme though! A PR is welcome!

**Comment by E3V3A** [comment]
@derhuerst  
Hi Jannis, 
Are you using this library for something else? If not I'm happy to shoot off some PR's adding (see #14) and adjusting the radar to metric standards.

**Comment by derhuerst** [comment]
Please keep it as feet, because the upstream source is in feet.
