### ISSUE TITLE
Improvement: Process additional JSON fields

### ISSUE THREAD

**Issue by E3V3A** [derhuerst/flightradar24-client#14]
I propose to also process the additional fields given in the JSON. 
Currently only [these fields](https://github.com/derhuerst/flightradar24-client/blob/master/lib/radar.js#L71-L88) are processed: 

```javascript
aircraft.push({
				// 10: timestamp, not needed
				// todo: 6, 14
				id,
				registration: d[9] || null,
				flight: d[13] || null,
				callsign: d[16] || null,
				origin: d[11] || null,
				destination: d[12] || null,
				latitude: d[1],
				longitude: d[2],
				altitude: d[4], // in feet
				bearing: d[3], // in degrees
				speed: d[5], // in knots
				model: d[8] || null,
				modeSCode: d[0] || null,
				radar: d[7]
})
```

But there are **18 fields** (0-17) in total:

```json
,"10572608":[
  "800B9C", 13.3638, 73.6369,
  91, 29500, 450,
  "6231", "F-VOCL1", "B738",
  "VT-GHD",1517871136,"DXB",
  "IXE","IX814",0,
  -2112, "AXB814", 0
]
```

Of these there are a few additional ones known:

* `d[10]` is the Unix Timestamp in Epoch format, which **is useful** for determining exactly when the data was obtained. 
* `d[6]` is the 4-digit ATC [Squawk](https://en.wikipedia.org/wiki/Transponder_(aeronautics)#Ident) code. Very useful for determining if aircraft is a military, in emergency etc.
* `d[15]` is the vertical speed in [ft/min]. 

Then there are two unknowns: 

* `d[14]` which seem to be either "0|1". 
* `d[17]` which is always `0` AFAICT.

**Comment by derhuerst** [comment]
Please add `d[10]` as `epoch` or `when`. Do you know *for sure* that the value represents the point in time the data was obtained?

Does `d[6]` represent the whole Squawk code or only a part of it?

**Comment by E3V3A** [comment]
> Do you know for sure that the value represents the point in time the data was obtained?

That we can never know, because it would depend on *how* the data was obtained. For ADS-B it should be the receiver time, but for MLAT or data obtained by other methods, such as non-professional feeds from ATC RADAR, it could certainly be delayed. (In the US you can get ATC feed, but its delayed for "security" measures ==profit.) 

Without a definite answer from F24 we simply have to assume they are feeding the best data available to them.

As for Squawk code, it only the 4-digit "code" and not any additional bits/info. 

The additional unknowns may be related to the `request` parameters, somehow. For example, it could be showing non-motorized gliders/balloons, or on/off ground etc. More investigation needed.

**Comment by derhuerst** [comment]
> Without a definite answer from F24 we simply have to assume they are feeding the best data available to them.

okay. you could argue that this library would make assumptions about the data if the field was called `recorded`. in line with #11, i would add this as `timestamp` or `epoch` field (i prefer `timestamp`).

> As for Squawk code, it only the 4-digit "code" and not any additional bits/info.

fine, let's add it as `squawkCode` then.

**Comment by derhuerst** [comment]
btw what's the difference between callsaign and squawk code?

**Comment by E3V3A** [comment]
* `callsign` is used to identify the aircraft by its ICAO | FAA code, it also tells something about the aircraft country and type and is used by ATC for easy verbal communication. 
* `Squawk` is a code that the pilot sets to indicate the type of flight for the ATC to understand. If set to 7500, it means that there is a hijack in progress.

**Comment by derhuerst** [comment]
thanks.
