### ISSUE TITLE
INFO: Added a new use of your module

### ISSUE THREAD

**Issue by E3V3A** [derhuerst/flightradar24-client#17]
@derhuerst 
Hi Jannis,

I've finally been able to put your client to proper use! Very nice. If you are familiar with the [MagicMirror](https://github.com/MichMich/MagicMirror) development, I have created a module to display current flights above a certain location, using the `radar()` function. It is called [MMM-FlightsAbove](https://github.com/E3V3A/MMM-FlightsAbove). 

Thanks again and cheers.
E:V:A

**Comment by derhuerst** [comment]
Nice to know that my libraries are being used! 💛 

I will add your project to the readme.
