### ISSUE TITLE
can it be used with react-native ?

### ISSUE THREAD

**Issue by omarDtp** [derhuerst/flightradar24-client#28]
Hello there,

is this library compatible to be used with react native? 
are you planning to implement the UI for flight radar when tracking a flight ?

Thank you

**Comment by derhuerst** [comment]
> is this library compatible to be used with react native?

It should be, as it uses `fetch-ponyfill` & `pinkie-promise` to be platform-independent:

https://github.com/derhuerst/flightradar24-client/blob/0d63e107e853713dad7885529ad2b39cecb87813/lib/radar.js#L4

But I haven't tried if it really is, please report your findings here if you try it!

> are you planning to implement the UI for flight radar when tracking a flight ?

No, this is not within the scope of this project. But you can browse the [dependent projects](https://github.com/derhuerst/flightradar24-client/network/dependents?package_id=UGFja2FnZS0xNjQ0MjcxNw%3D%3D) or build your own!

**Comment by derhuerst** [comment]
Please re-open if you have more questions related to this.
