### ISSUE TITLE
broken due to api changes on flightradar site

### ISSUE THREAD

**Issue by khassel** [derhuerst/flightradar24-client#36]
may related to #35 

the used endpoint https://data-live.flightradar24.com/zones/fcgi/feed.js (in `radar.js`) is now redirected to https://www.flightradar24.com/static/legacy/feed.json so this module does'nt work anymore.

Did not dig into the website if the new url is usable (may with changed parameters).

At the moment the other endpoint https://data-cloud.flightradar24.com/zones/fcgi/feed.js is still working so a quick fix would be to replace this ...

**Comment by FatPilot** [comment]
Thank you @khassel that worked for me!

**Comment by DeanCording** [comment]
Worked for me as well

**Comment by derhuerst** [comment]
Don't hesitate to submit a PR that adapts the endpoint!

**Comment by derhuerst** [comment]
Fix published as `flightradar24-client@1.0.1`.
