### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by E3V3A** [derhuerst/flightradar24-client#7]
Following your README we get the following error:

```bash
$ npm install flightradar24-client
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ flightradar24-client@0.2.0
added 17 packages in 15.042s
```
Maybe add these files...

**Comment by derhuerst** [comment]
first of all, these are only warnings. npm installed `flightradar24-client` just fine.

the warnings are about a file that npm would like to see in *your* directory. it is usually being used to install dependencies into JavaScript projects. your directory does not have such a `package.json` file.

**Comment by E3V3A** [comment]
> the warnings are about a file that npm would like to see in your directory. 

There is something weird about that idea. Why would it be so? I don't get this from any other npm package out there. So I guess, if it's not in *your* directory, it starts looking in mine.

**Comment by derhuerst** [comment]
I don't get this warning when installing `flightradar24-client` in a JavaScript project (containing a `package.json` file). Pay attention to the specific warning: It says "no such file or directory, [...] `/home/pi/package.json`".

**Comment by derhuerst** [comment]
Try with a new directory, run `npm init --yes` to generate a new `package.json` file. Then run `npm install flightradar24-client`.

If you still get an error then, please reopen this issue.
