### ISSUE TITLE
README -- add shebang and command to run the code

### ISSUE THREAD

**Issue by E3V3A** [derhuerst/flightradar24-client#8]
Please add some instructions how to use this.  
I.e. The steps from `git clone`, to terminal json output. Perhaps like this:

```bash
$  npm install flightradar24-client
...
$ # Edit the file below so that:
$ cat getplanes.js

#!/usr/bin/node
const radar = require('flightradar24-client/lib/radar')
radar(53, 13, 52, 14)
.then(console.log)
.catch(console.error)

$ # Run with:
$ ./getplanes.js

[ { id: '103b6cbc',
    registration: 'D-AKNT',
    flight: 'EW8102',
    callsign: 'EWG8102',
    origin: 'TXL',
    destination: 'BRU',
    latitude: 52.5271,
    longitude: 13.0341,
    altitude: 8450,
    bearing: 254,
    speed: 252,
    model: 'A319',
    modeSCode: '3C6DD4',
    radar: 'F-EDDT2' },
...
```

Everything else is great. Thanks!

**Comment by derhuerst** [comment]
Thanks for your feedback! I don't intend to tell people where and how to use `flightradar24-client` though. Also, using a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) (the `#!/usr/bin/node` thing) is only appropriate for command line tools.

**Comment by E3V3A** [comment]
@derhuerst 

My pleasure. I love this already and I hear you, but knowing nothing about your tool, it's hard to to test without first seeing what happens on CLI. Like in #10 .

**Comment by derhuerst** [comment]
You can always inspect and run the [example script](https://github.com/derhuerst/flightradar24-client/blob/faf206b5c6ae8d9018ba0b242b33f977396aeef7/example.js) using `node example.js`. Or you can copy-paste the code from the readme into a file an run it.

Using a shebang would enable you to do `./example.js`, but this is only makes sense for command line tools, not simple test scripts.

**Comment by derhuerst** [comment]
Please reopen if you have any more questions.
