### ISSUE TITLE
clarify the meaning of north, west, south, east

### ISSUE THREAD

**Issue by E3V3A** [derhuerst/flightradar24-client#9]
Please write more clearly that those numbers actually represent!
I think they mean the bounding box of:

- Northern edge `latitude`
- Western edge `longitude`
- Southern edge `latitude`
- Easter edge `longitude`

```js
# radar(north, west, south, east)
const radar = require('flightradar24-client/lib/radar')
radar(53, 13, 52, 14)
```

The fun part is of course converting distance (in km) to the correct **(lat,lon)**'s.

**Comment by derhuerst** [comment]
> Please write more clearly that those numbers actually represent!
> I think they mean the bounding box of:
>
> - Northern edge `latitude`
> - Western edge `longitude`
> - Southern edge `latitude`
> - Easter edge `longitude`

Yes, I think it would be helpful to add these. A PR is welcome!

**Comment by derhuerst** [comment]
> The fun part is of course converting distance (in km) to the correct **(lat,lon)**'s.

It's not the job of this library. You may have a different use case, and still want to use that data. [Turf](http://turfjs.org) is a well-tested geoprocessing library, that will help you with this.

**Comment by derhuerst** [comment]
done as of #12.
